# This is a config for E2B sandbox template.
# You can use template ID (s9yo9c7op02meuy18aea) or template name (vibe-nextjs-test-avi-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-avi-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-avi-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-avi-2')

team_id = "358baa4c-0bfb-4261-90c4-63b8958b027a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-avi-2"
template_id = "s9yo9c7op02meuy18aea"
